// 10 bits for texture index
const BARREL_TOP = 0
const BARREL_SIDE = 1
const BARREL_BOTTOM = 2
const BARREL_OPEN = 3
const BOOKSHELF = 4
const OAK_PLANKS = 5
const OAK_LOG = 6
const OAK_END = 7
const STRIPPED_OAK_LOG = 8
const STRIPPED_OAK_END = 9
const STONE = 10
const GRASS_BLOCK_TOP = 11
const GRASS_BLOCK_SIDE = 12
const DIRT_BLOCK = 13
const HAY_TOP = 14
const HAY_SIDE = 15
const GLASS = 16
const FURNACE_BOTTOM = 17
const FURNACE_SIDE = 18
const FURNACE_FRONT = 19
const FURNACE_FRONT_ON = 20
const MUSIC_BOX_TOP = 21
const MUSIC_BOX_SIDE = 22
const LOOM_TOP = 23
const LOOM_FRONT = 24
const LOOM_SIDE = 25
const COBBLESTONE = 26
const CRAFTING_TABLE_TOP = 27
const CRAFTING_TABLE_FRONT = 28
const CRAFTING_TABLE_SIDE = 29
const PUMPKIN_TOP = 30
const PUMPKIN_SIDE = 31

// 1 bit of precision leftover

export const blocks = {
  barrel: [BARREL_SIDE, BARREL_SIDE, BARREL_TOP, BARREL_BOTTOM, BARREL_SIDE, BARREL_SIDE],
  barrelOpen: [BARREL_SIDE, BARREL_SIDE, BARREL_OPEN, BARREL_BOTTOM, BARREL_SIDE, BARREL_SIDE],
  bookshelf: [BOOKSHELF, BOOKSHELF, OAK_PLANKS, OAK_PLANKS, BOOKSHELF, BOOKSHELF],
  cobblestone: [COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE],
  craftingTable: [CRAFTING_TABLE_SIDE, CRAFTING_TABLE_SIDE, CRAFTING_TABLE_TOP, OAK_PLANKS, CRAFTING_TABLE_FRONT, CRAFTING_TABLE_SIDE],
  dirt: [DIRT_BLOCK, DIRT_BLOCK, DIRT_BLOCK, DIRT_BLOCK, DIRT_BLOCK, DIRT_BLOCK],
  furnace: [FURNACE_SIDE, FURNACE_SIDE, FURNACE_BOTTOM, FURNACE_BOTTOM, FURNACE_SIDE, FURNACE_FRONT],
  furnaceOn: [FURNACE_SIDE, FURNACE_SIDE, FURNACE_BOTTOM, FURNACE_BOTTOM, FURNACE_SIDE, FURNACE_FRONT_ON],
  glass: [GLASS, GLASS, GLASS, GLASS, GLASS, GLASS],
  grass: [GRASS_BLOCK_SIDE, GRASS_BLOCK_SIDE, GRASS_BLOCK_TOP, DIRT_BLOCK, GRASS_BLOCK_SIDE, GRASS_BLOCK_SIDE],
  hay: [HAY_SIDE, HAY_SIDE, HAY_TOP, HAY_TOP, HAY_SIDE, HAY_SIDE],
  loom: [LOOM_SIDE, LOOM_SIDE, LOOM_TOP, OAK_PLANKS, LOOM_FRONT, LOOM_SIDE],
  musicBox: [MUSIC_BOX_SIDE, MUSIC_BOX_SIDE, MUSIC_BOX_TOP, MUSIC_BOX_TOP, MUSIC_BOX_SIDE, MUSIC_BOX_SIDE],
  oakLog: [OAK_LOG, OAK_LOG, OAK_END, OAK_END, OAK_LOG, OAK_LOG],
  oakPlanks: [OAK_PLANKS, OAK_PLANKS, OAK_PLANKS, OAK_PLANKS, OAK_PLANKS, OAK_PLANKS],
  pumpkin: [PUMPKIN_SIDE, PUMPKIN_SIDE, PUMPKIN_TOP, PUMPKIN_TOP, PUMPKIN_SIDE, PUMPKIN_SIDE],
  stone: [STONE, STONE, STONE, STONE, STONE, STONE],
  strippedOak: [STRIPPED_OAK_LOG, STRIPPED_OAK_LOG, STRIPPED_OAK_END, STRIPPED_OAK_END, STRIPPED_OAK_LOG, STRIPPED_OAK_LOG]
}

export const transLevel = {
  glass: 1
}

export const blockNames = Object.keys(blocks)
blockNames.forEach((n, i) => { blocks[n].index = i })
